# Generated by Django 3.1.12 on 2021-06-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCorreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('servicioDeseado', models.CharField(db_column='servicio_deseado', max_length=200)),
            ],
            options={
                'db_table': 'datos_correo',
                'ordering': ['-id'],
            },
        ),
    ]
